default:
  title: Hello-C-World
  author: TinyLab.org | 泰晓实验室
  font: Liberation Serif
  main: Liberation Serif
  bold: "{* Bold}"
  mono: Liberation Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  thanks: "\\url{http://TinyLab.org}是一个开放的嵌入式系统研发社区，致力于嵌入式Linux产品级系统解决方案的研发与交流。该书是其成员Wu Zhangjin/Falcon基于早年编写的一序列关于C语言编程的技术博客整理而成，现作为自由书籍发布，其项目首页为\\url{http://www.tinylab.org/project/hello-c-world/}。"
zh:
  title: C语言编程透视 
  author: TinyLab.org | 泰晓实验室
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: WenQuanYi Micro Hei
  main: WenQuanYi Micro Hei
  bold: WenQuanYi Micro Hei
  mono: WenQuanYi Micro Hei
  # AR is 文鼎字体，中文缺省 http://www.arphic.com/cn/home.html
  # http://www.debian.org/international/Chinese/software
  # AR PL UMing: 文鼎PL细上海宋 : 句号有问题
  # AR PL UKai: 文鼎PL中楷
  # AR PL SungtiL GB : 文鼎PL简报宋 ， * (item) 有问题！为空
  # AR PL KaitiM GB : 文鼎PL简中楷
  # WenQuanYi is 文泉驿 http://wenq.org/
  # WenQuanYi Bitmap Song: 点阵宋 (! had problem ?)
  # WenQuanYi Micro Hei：微米黑
  # WenQuanYi Zen Hei Mono：正黑
  # Adobe Song Std: Adobe 宋体 ， * (item) 有问题！为框
  #
  # default below
  #font: AR PL UMing CN 
  #bold: AR PL UKai CN
  #mono: AR PL UKai CN  
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "节"
  con: "目录"
  fig: "图 "
  tab: "表 "
  # 首段落空两格字。
  indent: "文文"
zh-tw:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: AR PL UMing TW
  main: AR PL UKai TW
  bold: AR PL UKai TW
  mono: AR PL UKai TW
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "節"
  dql: "『"
  dqr: "』"
  con: "目錄"
  fig: "圖 "
  tab: "表 "
  indent: "文"
ja:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
#  font: Japan
#  font: Sazanami Mincho
  font: IPAPMincho
  bold: VL PGothic
#  bold: Sazanami Gothic
#  bold: IPAPGothic
  mono: VL Gothic
  prechap: "第"
  postchap: "章"
  presect: ""
  postsect: "節"
  dql: "『"
  dqr: "』"
  con: "目次"
  fig: "図"
  tab: "表"
  indent: "あ"
ru:
  prechap: "Глава "
  presect: "Раздел "
  con: "Содержание"
  fig: "Рисунок "
  tab: "Таблица "
  dql: "«"
  dqr: "»"
cs:
  prechap: "Kapitola "
  presect: "Oddíl "
  dql: "„"
  dqr: "“"
  fig: "Obrázek "
  tab: "Tabulka "
fr:
  prechap: "Chapitre "
  presect: "Section "
  fig: "Figure "
  tab: "Tableau "
  font: Linux Libertine
  mono: Courier New
  con: "Table des matières"
  langrule: "\\frenchspacing\\usepackage{fontspec}\n\\fontspec[Ligatures={Common}]{Linux Libertine}\n"
  thanks: "Ce fichier PDF est la traduction française du livre Pro Git. Il est publié sous license Creative Commons Attribution-Non Commercial-Share Alike 3.0. J'espère que vous l'apprécierez, qu'il vous permettra d'apprendre à utiliser Git et que vous aiderez Apress en achetant le livre original sur Amazon : \\url{http://tinyurl.com/amazonprogit}"
  dql: "«\\,"
  dqr: "\\,»"
mk:
  fig: "Слика"
  con: "Содржина"
  prechap: "Поглавје"
  presect: "Секција"
  dql: "„"
  dqr: "“"
  tab: "Табела"
de:
  langrule: "\\frenchspacing"
  dql: "„"
  dqr: "“"
ko:
  langrule: "\\XeTeXlinebreakskip=0em plus 0.1em minus 0.01em\n\\XeTeXlinebreakpenalty=0"
  font: UnBatang
  bold: UnGraphic
  mono: UnDotum
  prechap: ""
  postchap: "장"
  presect: ""
  postsect: "절"
  con: "목차"
  fig: "그림"
  tab: "표"
be:
  prechap: "Глава "
  presect: "Раздзел "
  con: "Змест"
  fig: "Малюнак "
  tab: "Табліца "
